"""
ATLAS translations

Supported languages:
- no = Norwegian
- en = English
"""

TRANSLATIONS = {
    "no": {
        "language": "Språk", "settings": "Innstillinger", "dashboard": "Dashbord", "analysis": "Analyse", "markets": "Markeder", "portfolio": "Portefølje", "agents": "Agenter",
        "trading_mode": "Handelsmodus", "active_mode": "Aktiv modus", "advisor": "Rådgiver", "advisor_description": "ATLAS analyserer markedet, men legger ikke inn ordre.",
        "paper_trading": "Papirhandel", "paper_trading_upper": "PAPIRHANDEL", "paper_dry_run": "Papirhandel / Tørrkjøring", "paper_description": "ATLAS simulerer handler uten å legge inn ekte ordre.",
        "virtual_portfolio": "Virtuell portefølje", "virtual_capital": "Virtuell kapital", "total_equity": "Total egenkapital", "unrealized_pl": "Urealisert resultat", "total_pl": "Totalt resultat", "return": "Avkastning", "selected_asset": "Valgt aktivum", "no_news_found": "Ingen nyheter funnet.",
        "confidence": "Konfidens", "evidence": "Bevis", "ai_consensus": "AI-konsensus", "ai_decision": "AI-beslutning", "why_atlas": "Hvorfor ATLAS?", "watchlist": "Overvåkningsliste", "market_overview": "Markedsoversikt", "latest_news": "Siste nyheter", "capital": "Kapital", "cash": "Kontanter", "invested": "Investert", "positions": "Posisjoner", "technical_analysis": "Teknisk analyse",
        "price_above_ma20": "Prisen ligger over MA20.", "price_below_ma20": "Prisen ligger under MA20.", "ma20_above_ma50": "MA20 ligger over MA50.", "ma20_below_ma50": "MA20 ligger under MA50.", "overall_trend_bullish": "Den overordnede trenden er positiv.", "overall_trend_bearish": "Den overordnede trenden er negativ.", "mixed_market_trend": "Blandet markedstrend.", "waiting_confirmation": "Venter på bekreftelse.",
        "strong_revenue_growth": "Sterk inntektsvekst.", "revenue_growing": "Inntektene vokser.", "revenue_growth_weak": "Inntektsveksten er svak eller negativ.", "strong_profit_margin": "Sterk fortjenestemargin.", "company_profitable": "Selskapet er lønnsomt.", "profitability_weak": "Lønnsomheten er svak eller negativ.", "no_debt_data": "Ingen gjeldsgrad-data tilgjengelig.", "debt_manageable": "Gjeldsnivået ser håndterbart ut.", "debt_high": "Gjeldsnivået er relativt høyt.", "positive_free_cash_flow": "Selskapet genererer positiv fri kontantstrøm.", "free_cash_flow_weak": "Fri kontantstrøm er svak eller negativ.",
        "ai_news_sentiment": "AI-nyhetssentiment", "news_relevance": "Nyhetsrelevans", "market_impact": "Markedspåvirkning", "time_horizon": "Tidshorisont", "ai_confidence": "AI-konfidens", "analyzed_articles": "Analyserte {count} nyhetsartikler for {symbol}.", "trend": "Trend", "buy": "KJØP", "sell": "SELG", "hold": "HOLD", "news_analyst": "Nyhetsanalytiker", "technical_analyst": "Teknisk analytiker", "positive": "Positiv", "negative": "Negativ", "mixed": "Blandet", "bullish": "Positiv", "bearish": "Negativ", "neutral": "Nøytral", "running": "Kjører", "no_orders": "INGEN ORDRER", "live_orders": "Live-ordrer", "disabled": "DEAKTIVERT",
        "save_settings": "Lagre innstillinger", "configure_atlas": "Konfigurer hvordan ATLAS fungerer.", "safety": "Sikkerhet", "safety_description": "ATLAS kan ikke legge inn ekte ordre. Handelen forblir beskyttet så lenge denne innstillingen er deaktivert.", "on": "PÅ", "off": "AV", "ai_provider": "AI-leverandør", "active_provider": "Aktiv leverandør", "openai_description": "Bruk OpenAI til ATLAS AI-analyse.", "ollama_description": "Bruk lokal Ollama med qwen3:4b.", "language_norwegian": "Norsk", "language_english": "English",
        "accumulation": "Akkumulering", "accumulation_drop_pct": "Prisfall før nytt kjøp", "accumulation_description": "ATLAS kan øke en eksisterende posisjon først når prisen har falt angitt prosent fra siste faktiske kjøpspris.", "accumulation_range": "Tillatt verdi: 0,1–20,0 %.",
        "atlas_conviction": "ATLAS-overbevisning", "atlas_sees": "ATLAS ser", "robustness": "Robusthet", "consensus": "Enighet", "portfolio_summary": "Porteføljeoversikt", "cash_available": "Tilgjengelige kontanter", "total_return": "Total avkastning", "market_pulse": "Markedsbildet", "dashboard_universe": "Gjeldende markedsunivers · klikk på et aktivum for markedsterminalen", "full_market_view": "Full markedsoversikt", "opportunities": "ATLAS-muligheter", "ranked_candidates": "Rangerte kandidater fra oppdagelses- og beslutningslagene", "view_scanner": "Åpne skanneren", "asset": "Aktivum", "signal": "Signal", "discovery": "Funnscore", "why_it_matters": "Hvorfor dette er interessant", "top_ranked_candidate": "Høyest rangerte kandidat", "market_candidate": "Markedskandidat", "highest_current_ranking": "Høyeste ATLAS-rangering akkurat nå", "positive_decision_signal": "Positivt beslutningssignal", "downside_signal": "Negativt signal oppdaget", "mixed_evidence_watch": "Blandet grunnlag / følg med", "no_ranked_candidates": "Ingen rangerte kandidater er tilgjengelige ennå. Åpne skanneren for å oppdatere og se markedet.",
        "intelligence": "ATLAS-analyse", "agreement": "Enighet", "level": "Nivå", "dominant_influence": "Dominerende påvirkning", "waiting_evidence": "ATLAS venter på nok grunnlag til å forklare den nåværende beslutningen.", "manage": "Administrer", "news_events": "Nyheter og hendelser", "latest_context": "Siste kontekst for valgt aktivum", "no_news_available": "Ingen nyheter er tilgjengelige nå.", "live_market": "Live-marked", "read_only_market_view": "Skrivebeskyttet markedsvisning", "signal_informational": "ATLAS-signalet er informativt; papirhandel er fortsatt grensen for faktisk utførelse.", "virtual_paper_portfolio": "Virtuell papirportefølje", "scanner": "ATLAS-skanner", "live_refresh": "Live-oppdatering", "manual_refresh": "Manuell oppdatering", "current_price": "Gjeldende pris", "confidence_lower": "konfidens",
        "paper_account_overview": "Oversikt over papirhandelskonto", "profit_vault": "Resultatreserve", "performance": "Ytelse", "symbol": "Symbol", "value": "Verdi", "no_open_positions": "Ingen åpne posisjoner", "no_active_paper_positions": "ATLAS har ingen aktive papirhandelsposisjoner ennå.", "trade_history": "Handelshistorikk", "no_trades_yet": "Ingen handler ennå", "no_paper_trades": "ATLAS har ikke utført noen papirhandler ennå.",
        "scanner_title": "ATLAS-skanner", "scanner_description": "Markedets oppdagelseslag for aksjer og krypto. Kandidater går videre til tidshorisont, algoritmer, AI-analyse, risiko og kostnad.", "scanner_connected": "Skannermotor tilkoblet", "stocks": "Aksjer", "crypto": "Krypto", "research_only": "Kun analyse", "stocks_description": "Forberedt for momentum, relativt volum, utbrudd, katalysatorer, likviditet og free float.", "crypto_description": "Forberedt for 24/7-skanning med momentum, volum, utbrudd og likviditet.", "research_only_description": "Skanneresultater er kandidater, ikke ordre. Handel forblir papirhandel/tørrkjøring.", "live_scanner_feed": "Live skannerstrøm", "observations": "Observasjoner", "eligible_candidates": "Kvalifiserte kandidater", "scanner_filters": "Skannerfiltre og sortering", "search_symbol": "Søk symbol", "market": "Marked", "all": "Alle", "catalyst": "Katalysator", "with_catalyst": "Med katalysator", "without_catalyst": "Uten katalysator", "sort_by": "Sorter etter", "score": "Score", "momentum": "Momentum", "volume": "Volum", "breakout": "Utbrudd", "liquidity": "Likviditet", "showing_candidates": "Viser {visible} av {total} kandidater", "open_chart": "Åpne diagram →", "no_market_observations": "Ingen markedsobservasjoner er koblet til ennå", "scanner_empty_description": "ScannerService er nå koblet til dashboard-kontrakten. Neste steg er å mate den med ekte, skrivebeskyttede markedsdata — uten å simulere kandidater.", "decision_pipeline": "ATLAS-beslutningsflyt", "find_candidates": "Finn kandidater", "horizon_day_swing_position": "Dag / Swing / Posisjon", "technical_signals": "Tekniske signaler", "deep_analysis": "Dyp analyse", "before_paper_trade": "Før papirhandel", "current_scanner_rules": "Gjeldende skannerregler", "stock_min_price": "Minimumspris for aksjer", "minimum_average_volume": "Minimum gjennomsnittlig volum", "minimum_current_volume": "Minimum nåværende volum", "required": "Påkrevd",
        "agents_description": "Ytelse og adaptive vekter for ATLAS-analytikere.", "predictions": "Prediksjoner", "correct": "Riktige", "wrong": "Feil", "accuracy": "Treffsikkerhet", "current_weight": "Gjeldende vekt", "safety_limit": "60 % sikkerhetsgrense", "learning": "Læring", "adaptive": "Adaptiv", "building_history": "Bygger historikk", "why_this_weight": "Hvorfor denne vekten?", "stabilized": "Stabilisert", "average": "Gjennomsnitt", "no_performance_history": "Ingen ytelseshistorikk ennå", "no_agent_predictions_evaluated": "ATLAS har ennå ikke evaluert noen agentprediksjoner.",
    },
    "en": {
        "language": "Language", "settings": "Settings", "dashboard": "Dashboard", "analysis": "Analysis", "markets": "Markets", "portfolio": "Portfolio", "agents": "Agents",
        "trading_mode": "Trading Mode", "active_mode": "Active mode", "advisor": "Advisor", "advisor_description": "ATLAS analyzes the market but does not place orders.", "paper_trading": "Paper Trading", "paper_trading_upper": "PAPER TRADING", "paper_dry_run": "Paper / Dry Run", "paper_description": "ATLAS simulates trades without placing real orders.", "virtual_portfolio": "Virtual portfolio", "virtual_capital": "Virtual capital", "total_equity": "Total Equity", "unrealized_pl": "Unrealized P/L", "total_pl": "Total P/L", "return": "Return", "selected_asset": "Selected Asset", "no_news_found": "No news found.",
        "confidence": "Confidence", "evidence": "Evidence", "ai_consensus": "AI Consensus", "ai_decision": "AI Decision", "why_atlas": "Why ATLAS?", "watchlist": "Watchlist", "market_overview": "Market overview", "latest_news": "Latest News", "capital": "Capital", "cash": "Cash", "invested": "Invested", "positions": "Positions", "technical_analysis": "Technical Analysis",
        "price_above_ma20": "Price is above MA20.", "price_below_ma20": "Price is below MA20.", "ma20_above_ma50": "MA20 is above MA50.", "ma20_below_ma50": "MA20 is below MA50.", "overall_trend_bullish": "Overall trend is bullish.", "overall_trend_bearish": "Overall trend is bearish.", "mixed_market_trend": "Mixed market trend.", "waiting_confirmation": "Waiting for confirmation.", "strong_revenue_growth": "Strong revenue growth.", "revenue_growing": "Revenue is growing.", "revenue_growth_weak": "Revenue growth is weak or negative.", "strong_profit_margin": "Strong profit margin.", "company_profitable": "Company is profitable.", "profitability_weak": "Profitability is weak or negative.", "no_debt_data": "No debt-to-equity data available.", "debt_manageable": "Debt level appears manageable.", "debt_high": "Debt level is relatively high.", "positive_free_cash_flow": "Company generates positive free cash flow.", "free_cash_flow_weak": "Free cash flow is weak or negative.",
        "ai_news_sentiment": "AI news sentiment", "news_relevance": "News relevance", "market_impact": "Market impact", "time_horizon": "Time horizon", "ai_confidence": "AI confidence", "analyzed_articles": "Analyzed {count} news article(s) for {symbol}.", "trend": "Trend", "buy": "BUY", "sell": "SELL", "hold": "HOLD", "news_analyst": "News Analyst", "technical_analyst": "Technical Analyst", "positive": "Positive", "negative": "Negative", "mixed": "Mixed", "bullish": "Bullish", "bearish": "Bearish", "neutral": "Neutral", "running": "Running", "no_orders": "NO ORDERS", "live_orders": "Live orders", "disabled": "DISABLED",
        "save_settings": "Save Settings", "configure_atlas": "Configure how ATLAS operates.", "safety": "Safety", "safety_description": "ATLAS cannot place real orders. Trading remains protected while this setting is disabled.", "on": "ON", "off": "OFF", "ai_provider": "AI Provider", "active_provider": "Active provider", "openai_description": "Use OpenAI for ATLAS AI analysis.", "ollama_description": "Use local Ollama with qwen3:4b.", "language_norwegian": "Norsk", "language_english": "English",
        "accumulation": "Accumulation", "accumulation_drop_pct": "Price drop before next buy", "accumulation_description": "ATLAS may add to an existing position only after the price has fallen the specified percentage from the last actual purchase price.", "accumulation_range": "Allowed value: 0.1–20.0%.",
        "atlas_conviction": "ATLAS Conviction", "atlas_sees": "ATLAS sees", "robustness": "Robustness", "consensus": "Consensus", "portfolio_summary": "Portfolio summary", "cash_available": "Cash available", "total_return": "Total return", "market_pulse": "Market Pulse", "dashboard_universe": "Current dashboard universe · click any asset for the Market Terminal", "full_market_view": "Full market view", "opportunities": "ATLAS Opportunities", "ranked_candidates": "Ranked candidates from discovery and decision layers", "view_scanner": "View scanner", "asset": "Asset", "signal": "Signal", "discovery": "Discovery", "why_it_matters": "Why it matters", "top_ranked_candidate": "Top ranked candidate", "market_candidate": "Market candidate", "highest_current_ranking": "Highest current ATLAS ranking", "positive_decision_signal": "Positive decision signal", "downside_signal": "Downside signal detected", "mixed_evidence_watch": "Mixed evidence / watch", "no_ranked_candidates": "No ranked candidates are available yet. Open Scanner to refresh and inspect the market universe.",
        "intelligence": "ATLAS Intelligence", "agreement": "Agreement", "level": "Level", "dominant_influence": "Dominant influence", "waiting_evidence": "ATLAS is waiting for enough evidence to explain the current decision.", "manage": "Manage", "news_events": "News & Events", "latest_context": "Latest context for the selected asset", "no_news_available": "No news is currently available.", "live_market": "Live Market", "read_only_market_view": "Read-only market view", "signal_informational": "ATLAS signal is informational; paper trading remains the execution boundary.", "virtual_paper_portfolio": "Virtual paper portfolio", "scanner": "ATLAS Scanner", "live_refresh": "Live refresh", "manual_refresh": "Manual refresh", "current_price": "Current price", "confidence_lower": "confidence",
        "paper_account_overview": "Paper-trading account overview", "profit_vault": "Profit Vault", "performance": "Performance", "symbol": "Symbol", "value": "Value", "no_open_positions": "No open positions", "no_active_paper_positions": "ATLAS has no active paper-trading positions yet.", "trade_history": "Trade History", "no_trades_yet": "No trades yet", "no_paper_trades": "ATLAS has not executed any paper trades yet.",
        "scanner_title": "ATLAS Scanner", "scanner_description": "Market discovery layer for stocks and crypto. Candidates move on to horizon, algorithms, AI analysis, risk and cost.", "scanner_connected": "Scanner engine connected", "stocks": "Stocks", "crypto": "Crypto", "research_only": "Research only", "stocks_description": "Prepared for momentum, relative volume, breakouts, catalysts, liquidity and float.", "crypto_description": "Prepared for 24/7 scanning with momentum, volume, breakout and liquidity.", "research_only_description": "Scanner results are candidates, not orders. Trading remains paper/dry-run.", "live_scanner_feed": "Live scanner feed", "observations": "Observations", "eligible_candidates": "Eligible candidates", "scanner_filters": "Scanner filters and sorting", "search_symbol": "Search symbol", "market": "Market", "all": "All", "catalyst": "Catalyst", "with_catalyst": "With catalyst", "without_catalyst": "Without catalyst", "sort_by": "Sort by", "score": "Score", "momentum": "Momentum", "volume": "Volume", "breakout": "Breakout", "liquidity": "Liquidity", "showing_candidates": "Showing {visible} of {total} candidates", "open_chart": "Open chart →", "no_market_observations": "No market observations are connected yet", "scanner_empty_description": "ScannerService is now connected to the dashboard contract. Next step is to feed it real, read-only market data — without simulating candidates.", "decision_pipeline": "ATLAS decision pipeline", "find_candidates": "Find candidates", "horizon_day_swing_position": "Day / Swing / Position", "technical_signals": "Technical signals", "deep_analysis": "Deep analysis", "before_paper_trade": "Before paper trade", "current_scanner_rules": "Current scanner rules", "stock_min_price": "Stock minimum price", "minimum_average_volume": "Minimum average volume", "minimum_current_volume": "Minimum current volume", "required": "Required",
        "agents_description": "Performance and adaptive weights for ATLAS analysts.", "predictions": "Predictions", "correct": "Correct", "wrong": "Wrong", "accuracy": "Accuracy", "current_weight": "Current Weight", "safety_limit": "60% safety limit", "learning": "Learning", "adaptive": "Adaptive", "building_history": "Building history", "why_this_weight": "Why this weight?", "stabilized": "Stabilized", "average": "Average", "no_performance_history": "No performance history yet", "no_agent_predictions_evaluated": "ATLAS has not evaluated any agent predictions yet.",
    },
}


def translate(language: str, key: str) -> str:
    """Return a translated string, falling back to English."""
    language = language if language in TRANSLATIONS else "en"
    return TRANSLATIONS[language].get(key, TRANSLATIONS["en"].get(key, key))


def get_translations(language: str) -> dict[str, str]:
    """Return the translation dictionary for a language."""
    language = language if language in TRANSLATIONS else "en"
    return TRANSLATIONS[language].copy()
